# Generated by Django 5.0.3 on 2024-06-16 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_fname_customer_fist_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='fist_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='last_lname',
            new_name='lname',
        ),
    ]
